# https://taskfile.dev

version: "3"

includes:
  prez:
    taskfile: ./prez/Taskfile.yml
    dir: ./prez

vars:
  COMPOSE_FILE: docker-compose.yml
  VOCPUB_VERSION: "4.10"

tasks:
  default:
    cmd: task -a

  stack:build:
    cmd: docker compose -f {{.COMPOSE_FILE}} build

  stack:up:
    cmd: docker compose -f {{.COMPOSE_FILE}} up -d

  stack:down:
    cmd: docker compose -f {{.COMPOSE_FILE}} down

  stack:clean:
    cmd: docker compose -f {{.COMPOSE_FILE}} down -v

  validate:
    cmd: |
      for file in vocabularies/*.ttl; do
        echo -e "\nValidating $file..."
        pyshacl --allow-warnings --shapes vocpub.ttl "$file"
        if [ $? -ne 0 ]; then
          echo "Validation failed for $file"
          exit 1
        fi
      done

  ci:test:
    cmd: |
      act \
        --container-architecture linux/amd64 \
        --workflows .github/workflows/release.yml \
        -e .github/act/release-event.json \
        --container-daemon-socket /var/run/docker.sock

  ci:test-static-web-app:
    cmd: |
      act \
        --container-architecture linux/amd64 \
        --workflows .github/workflows/release.yml \
        -e .github/act/release-event.json \
        --container-daemon-socket /var/run/docker.sock \
        --job deploy-to-azure-static-web-app
