name: Validate

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vocabs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prez
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: prez/pyproject.toml

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"
          enable-cache: true

      - name: Validate vocabularies
        run: task vocabs:validate
